name: Create Beta Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
     runs-on: macos-15
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (packages)
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip

      - name: Select Xcode 16
        run: | 
          sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
          mkdir upload
          sed -i '' 's/MARKETING_VERSION = \(.*\);/MARKETING_VERSION = \1-'$(git rev-parse --short HEAD)';/g' ./feather.xcodeproj/project.pbxproj
          sed -i '' '/func application(/a\
          Preferences.beta = true
          ' iOS/Delegates/AppDelegate.swift

      - name: Compile Feather
        run: | 
          make package
          mv packages/* upload/

      - name: Upload file to Litterbox (Catbox)
        id: upload_catbox
        run: |
          LINK=$(curl -F "reqtype=fileupload" -F "time=12h" -F "fileToUpload=@upload/Feather.ipa" https://litterbox.catbox.moe/resources/internals/api.php)
          echo "catbox_link=$LINK" >> $GITHUB_ENV

      - name: Send Discord build message
        run: |
          COMMIT_HASH=$(git log -1 --pretty=format:'%h') &&
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s') &&
          (
          curl "${{ secrets.B_WEBHOOK }}" -sS -H "Content-Type:application/json" -X POST -d '{
            "content": "@everyone New build available!",
            "embeds":[
              {
                "title":"${{ github.repository }} [Build ${{ github.run_number }}]",
                "description":"[`'"$COMMIT_HASH"'`](https://github.com/${{ github.repository }}/commit/'"$COMMIT_HASH"') '"$COMMIT_MESSAGE"'",
                "url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "color":6648790,
                "author":{
                  "name":"${{ github.actor }}",
                  "icon_url":"https://github.com/${{ github.actor }}.png"
                }
              }
            ],
            "attachments":[],
            "components":[
              {
                "type":1,
                "components":[
                  {
                    "type":2,
                    "url":"${{ env.catbox_link }}",
                    "label":"Download",
                    "style":5
                  }
                ]
              }
            ]
          }' || true
          )

