# this is inspired (and copied) from https://github.com/Equicord/Equicord/blob/main/.github/workflows/syncMain.yml

name: Sync Upstream Repository

env:
  WORKFLOW_TOKEN: ${{ secrets.SYNC_TOKEN }}
  UPSTREAM_URL: "https://github.com/khcrysalis/Feather.git"
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "main"

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Feather
        id: sync
        uses: verticalsync/sync-upstream-repo@master
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
